import { ActionSchemaType, NotificationsSchemaType, StartupSchemaType } from '../schema';
import { UserSchemaType } from '../schema';
import { Types } from 'mongoose';

type SeedAction = ActionSchemaType & {
  _id: Types.ObjectId;
};

type SeedNotification = Omit<NotificationsSchemaType, 'actions'> & {
  _id: Types.ObjectId;
  actions: SeedAction[];
};

type SeedStartup = StartupSchemaType &
  Omit<UserSchemaType, 'notifications'> & {
    _id: Types.ObjectId;
    notifications: SeedNotification[];
  };

export const startupsData: SeedStartup[] = [
  {
    _id: new Types.ObjectId('6873e386fe67663835ad869a'),
    email: 'merlin@example.com',
    createdAt: new Date('2025-07-13T16:49:10.157Z'),
    title: 'Personio',
    aboutUs: 'We are a young startup providing HR functionality as a Service',
    contactPersonNameLast: 'Merlin',
    contactPersonNameFirst: 'Max',
    contactPersonPicture: '/seedImages/contactPersonPictureMaxMartens.webp',
    industry: 'HR',
    addressCity: 'Berlin',
    addressCountry: 'Germany',
    fundingStatus: new Types.ObjectId('0000000000000000000c0000'),
    fulltimeEmployeesNum: 50,
    foundingYear: 2018,
    revenuePerYearEUR: 400000,
    imprintUrl: 'https://personio.de/impressum',
    websiteUrl: 'https://personio.de',
    logoUrl: '/seedImages/logoUrlMaxMartens.webp',
    stripeCustomerId: 'cus_ShfvEDIIFvyj68',
    stripePriceId: 'price_1RfLHnFQr2Nl7IwIOQ1GJow5',
    stripeSubscriptionExpiryDate: new Date('2025-08-18T15:52:12.000Z'),
    wiseUpSubscriptionTier: 'gold',
    monthlyConnectionBalance: 30,
    permanentConnectionBalance: 0,
    jobPostings: [new Types.ObjectId('6873e5bafe67663835ad86e8')],
    notifications: [],
    userType: 'Startup',
  },
  {
    _id: new Types.ObjectId('6873e994fe67663835ad879b'),
    email: 'weber@example.com',
    createdAt: new Date('2025-07-13T17:15:00.459Z'),
    title: 'Pacta',
    aboutUs: 'We do some legal stuff, like checking contracts and so on.',
    contactPersonNameLast: 'Weber',
    contactPersonNameFirst: 'Janine',
    contactPersonPicture: '/seedImages/contactPersonPictureJanineWeber.webp',
    industry: 'Legal',
    addressCity: 'Munich',
    addressCountry: 'Germany',
    fundingStatus: new Types.ObjectId('0000000000000000000a0000'),
    fulltimeEmployeesNum: 150,
    foundingYear: 2010,
    revenuePerYearEUR: 50000000,
    imprintUrl: 'https://pacta.ai/',
    websiteUrl: 'https://pacta.ai/impressum',
    logoUrl: '/seedImages/logoUrlJanineWeber.webp',
    stripeCustomerId: 'cus_ShfdYrLmPciPAI',
    stripePriceId: 'price_1RfLGoFQr2Nl7IwILNAVc59H',
    stripeSubscriptionExpiryDate: new Date('2025-08-18T15:34:24.000Z'),
    wiseUpSubscriptionTier: 'silver',
    monthlyConnectionBalance: 10,
    permanentConnectionBalance: 0,
    jobPostings: [new Types.ObjectId('6873ed13fe67663835ad880b')],
    notifications: [],
    userType: 'Startup',
  },
  {
    _id: new Types.ObjectId('6874d2c2fe67663835ad8a72'),
    email: 'berger@example.com',
    createdAt: new Date('2025-07-14T09:49:54.527Z'),
    title: 'FinScale',
    aboutUs: `FinScale is a lean, fast-moving fintech startup led by ambitious founders like Clara Berger. With a small, agile team, we focus on rapidly developing innovative financial solutions while staying budget-conscious and compliance-ready. We value trusted domain expertise, speed, and adaptability to bring ideas to life without the overhead of traditional structures.`,
    contactPersonNameLast: 'Berger',
    contactPersonNameFirst: 'Clara',
    contactPersonPicture: '/seedImages/contactPersonPictureClaraBerger.webp',
    industry: 'Finance',
    addressCity: 'Berlin',
    addressCountry: 'Germany',
    fundingStatus: new Types.ObjectId('000000000000000000040000'),
    fulltimeEmployeesNum: 5,
    foundingYear: 2019,
    revenuePerYearEUR: 500000,
    imprintUrl: 'finscale.com/impressum',
    websiteUrl: 'finscale.com',
    logoUrl: '/seedImages/logoUrlClaraBerger.webp',
    stripeCustomerId: 'cus_ShffLW5OKkRW4l',
    stripePriceId: 'price_1Reh7MFQr2Nl7IwIQ3JMXnvU',
    stripeSubscriptionExpiryDate: new Date('2025-08-18T15:36:33.000Z'),
    wiseUpSubscriptionTier: 'free',
    monthlyConnectionBalance: 1,
    permanentConnectionBalance: 0,
    jobPostings: [new Types.ObjectId('6874d4acfe67663835ad8ac9')],
    notifications: [],
    userType: 'Startup',
  },
  {
    _id: new Types.ObjectId('687a73998e2824283485784d'),
    email: 'anna.klein@example.com',
    createdAt: new Date('2025-07-18T16:17:29.988Z'),
    title: 'BankTech',
    aboutUs: 'We build smart compliance tooling for modern banks.',
    contactPersonNameFirst: 'Anna',
    contactPersonNameLast: 'Klein',
    contactPersonPicture: '/seedImages/contactPersonPictureAnnaKlein.webp',
    industry: 'FinTech',
    addressCity: 'Munich',
    addressCountry: 'Germany',
    fundingStatus: new Types.ObjectId('000000000000000000050000'),
    fulltimeEmployeesNum: 12,
    foundingYear: 2020,
    revenuePerYearEUR: 1200000,
    imprintUrl: 'banktech.io/impressum',
    websiteUrl: 'banktech.io',
    logoUrl: '/seedImages/logoUrlAnnaKlein.webp',
    stripeCustomerId: 'cus_ShgS3N5cUYnjbu',
    stripePriceId: 'price_1RfLGoFQr2Nl7IwILNAVc59H',
    stripeSubscriptionExpiryDate: new Date('2025-08-18T16:28:16.000Z'),
    wiseUpSubscriptionTier: 'silver',
    monthlyConnectionBalance: 10,
    permanentConnectionBalance: 0,
    jobPostings: [new Types.ObjectId('687a77b08e28242834857875')],
    notifications: [],
    userType: 'Startup',
  },
  {
    _id: new Types.ObjectId('687a78788e28242834857931'),
    email: 'bruno.schmidt@example.com',
    createdAt: new Date('2025-07-18T16:38:16.279Z'),
    title: 'GreenTech',
    aboutUs: 'We are developing solar-plus-storage systems for urban rooftops.',
    contactPersonNameFirst: 'Bruno',
    contactPersonNameLast: 'Schmidt',
    contactPersonPicture: '/seedImages/contactPersonPictureBrunoSchmidt.webp',
    industry: 'CleanTech',
    addressCity: 'Berlin',
    addressCountry: 'Germany',
    fundingStatus: new Types.ObjectId('000000000000000000040000'),
    fulltimeEmployeesNum: 8,
    foundingYear: 2023,
    revenuePerYearEUR: 450000,
    imprintUrl: 'https://greentech.example.com/impressum',
    websiteUrl: 'https://greentech.example.com',
    logoUrl: '/seedImages/logoUrlBrunoSchmidt.webp',
    stripeCustomerId: 'cus_ShgiplOTJjWf0i',
    stripePriceId: 'price_1RfLHnFQr2Nl7IwIOQ1GJow5',
    stripeSubscriptionExpiryDate: new Date('2025-08-18T16:41:00.000Z'),
    wiseUpSubscriptionTier: 'gold',
    monthlyConnectionBalance: 30,
    permanentConnectionBalance: 0,
    jobPostings: [
      new Types.ObjectId('687a7a318e28242834857959'),
      new Types.ObjectId('687a7af98e28242834857a6c'),
    ],
    notifications: [],
    userType: 'Startup',
  },
  {
    _id: new Types.ObjectId('687a7b9b8e28242834857bbc'),
    email: 'carla.mueller@example.com',
    createdAt: new Date('2025-07-18T16:51:39.665Z'),
    title: 'HealthSync',
    aboutUs: 'Connecting patient data across healthcare providers.',
    contactPersonNameFirst: 'Carla',
    contactPersonNameLast: 'Müller',
    contactPersonPicture: '/seedImages/contactPersonPictureCarlaMueller.webp',
    industry: 'HealthTech',
    addressCity: 'Hamburg',
    addressCountry: 'Germany',
    fundingStatus: new Types.ObjectId('000000000000000000030000'),
    fulltimeEmployeesNum: 6,
    foundingYear: 2025,
    revenuePerYearEUR: 30000,
    imprintUrl: 'https://healthsync.example.com/impressum',
    websiteUrl: 'https://healthsync.example.com',
    logoUrl: '/seedImages/logoUrlCarlaMueller.webp',
    stripeCustomerId: 'cus_ShguzYXARHHUF5',
    stripePriceId: 'price_1Reh7MFQr2Nl7IwIQ3JMXnvU',
    stripeSubscriptionExpiryDate: new Date('2025-08-18T16:53:11.000Z'),
    wiseUpSubscriptionTier: 'free',
    monthlyConnectionBalance: 1,
    permanentConnectionBalance: 0,
    jobPostings: [new Types.ObjectId('687a7cd28e28242834857be3')],
    notifications: [],
    userType: 'Startup',
  },
];
