/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HireInviteAction
 */
export interface HireInviteAction {
    /**
     * 
     * @type {string}
     * @memberof HireInviteAction
     */
    action: HireInviteActionActionEnum;
}


/**
 * @export
 */
export const HireInviteActionActionEnum = {
    Accept: 'accept',
    Decline: 'decline'
} as const;
export type HireInviteActionActionEnum = typeof HireInviteActionActionEnum[keyof typeof HireInviteActionActionEnum];


/**
 * Check if a given object implements the HireInviteAction interface.
 */
export function instanceOfHireInviteAction(value: object): value is HireInviteAction {
    if (!('action' in value) || value['action'] === undefined) return false;
    return true;
}

export function HireInviteActionFromJSON(json: any): HireInviteAction {
    return HireInviteActionFromJSONTyped(json, false);
}

export function HireInviteActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): HireInviteAction {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
    };
}

export function HireInviteActionToJSON(json: any): HireInviteAction {
    return HireInviteActionToJSONTyped(json, false);
}

export function HireInviteActionToJSONTyped(value?: HireInviteAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
    };
}

