/* tslint:disable */
/* eslint-disable */
/**
 * Retirement‐Matching API
 * REST endpoints for user auth (via magic‐link), retirees, career elements, reference data, startups, job postings, matching, conversations, and hire invites. Uses a JWT set in a cookie. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HireInviteRequest
 */
export interface HireInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof HireInviteRequest
     */
    retireeId: string;
}

/**
 * Check if a given object implements the HireInviteRequest interface.
 */
export function instanceOfHireInviteRequest(value: object): value is HireInviteRequest {
    if (!('retireeId' in value) || value['retireeId'] === undefined) return false;
    return true;
}

export function HireInviteRequestFromJSON(json: any): HireInviteRequest {
    return HireInviteRequestFromJSONTyped(json, false);
}

export function HireInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HireInviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'retireeId': json['retireeId'],
    };
}

export function HireInviteRequestToJSON(json: any): HireInviteRequest {
    return HireInviteRequestToJSONTyped(json, false);
}

export function HireInviteRequestToJSONTyped(value?: HireInviteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'retireeId': value['retireeId'],
    };
}

